# This is a basic workflow to help you get started with Actions

name: Deploy Prod

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          mkdir -p ~/.ssh
          ssh-add - <<< "${{ secrets.DEPLOYMENT_KEY }}"
          touch ~/.ssh/known_hosts
          cat scripts/known_hosts >> ~/.ssh/known_hosts
          
      - name: copy from staging to production
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh -t pacosako@pacoplay.com "./update-prod.sh"
